[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"

[functions."send-round-reminders"]
  schedule = "0 * * * *"

[functions."delete-past-rounds"]
  schedule = "0 * * * *"
